Repository openkruise/kruise-tools, pull requests merged in 2021-11, with the labels that each got.

#27 add expose cmd for cloneset
  README.md
  go.mod
  go.sum
  pkg/cmd/cmd.go
  pkg/cmd/expose/expose.go
  pkg/cmd/expose/expose_test.go
  pkg/cmd/set/set_image.go
  pkg/internal/polymorphichelpers/mapbasedselectorforobject.go
  pkg/internal/polymorphichelpers/protocolsforobject.go
  pkg/resource/builder.go
  pkg/resource/builder_test.go
  pkg/resource/client.go
  pkg/resource/crd_finder.go
  pkg/resource/crd_finder_test.go
  pkg/resource/doc.go
  pkg/resource/dry_run_verifier.go
  pkg/resource/dry_run_verifier_test.go
  pkg/resource/fake.go
  pkg/resource/helper.go
  pkg/resource/helper_test.go
  pkg/resource/interfaces.go
  pkg/resource/mapper.go
  pkg/resource/metadata_decoder.go
  pkg/resource/result.go
  pkg/resource/scheme.go
  pkg/resource/scheme_test.go
  pkg/resource/selector.go
  pkg/resource/visitor.go
  pkg/resource/visitor_test.go
Labels: lgtm, approved, size/XXL

#28 Remove useless controller-runtime manager and fix lint errors
  .github/workflows/ci.yaml
  .golangci.yml
  Makefile
  go.mod
  go.sum
  pkg/api/api.go
  pkg/cmd/expose/expose.go
  pkg/cmd/rollout/rollout.go
  pkg/cmd/rollout/rollout_history.go
  pkg/cmd/rollout/rollout_pause.go
  pkg/cmd/rollout/rollout_restart.go
  pkg/cmd/rollout/rollout_resume.go
  pkg/cmd/rollout/rollout_status.go
  pkg/cmd/rollout/rollout_undo.go
  pkg/cmd/scaledown/scaledown.go
  pkg/cmd/scaledown/scaledown_cloneset.go
  pkg/cmd/set/env/env_resolve.go
  pkg/cmd/set/helper.go
  pkg/cmd/set/set_env.go
  pkg/cmd/set/set_env_test.go
  pkg/cmd/set/set_image.go
  pkg/cmd/set/set_resources.go
  pkg/cmd/set/set_selector.go
  pkg/cmd/set/set_selector_test.go
  pkg/cmd/set/set_serviceaccount.go
  pkg/cmd/set/set_subject_test.go
  pkg/cmd/util/helpers.go
  pkg/conversion/cloneset_convertion.go
  pkg/creation/cloneset/cloneset_creation.go
  pkg/fetcher/advanced_sts.go
  pkg/fetcher/cloneset.go
  pkg/internal/polymorphichelpers/canbeexposed.go
  pkg/internal/polymorphichelpers/helpers.go
  pkg/internal/polymorphichelpers/history.go
  pkg/internal/polymorphichelpers/historyviewer.go
  pkg/internal/polymorphichelpers/interface.go
  pkg/internal/polymorphichelpers/objectpauser.go
  pkg/internal/polymorphichelpers/objectresumer.go
  pkg/internal/polymorphichelpers/rollback.go
  pkg/internal/polymorphichelpers/rollbacker.go
  pkg/internal/polymorphichelpers/updatepodspec.go
  pkg/migration/api.go
  pkg/migration/cloneset/cloneset_migration.go
  pkg/migration/cloneset/event_handlers.go
  pkg/utils/logs/logs.go
  pkg/version/version.go
  version.sh
Labels: lgtm, approved, size/XL

#29 Remove useless sub commands
  Makefile
  pkg/cmd/cmd.go
  pkg/cmd/expose/expose.go
Labels: lgtm, approved, size/M

#30 modify release.yaml and prepare for krew
  .github/workflows/release.yaml
Labels: lgtm, approved, size/L

#32 fix release.yaml
  .github/workflows/release.yaml
Labels: lgtm, approved, size/XS

#33 Fix/release yaml
  .github/workflows/release.yaml
Labels: lgtm, approved, size/XS
