Repository openkruise/kruise-tools, pull requests merged in 2021-07, with the labels that each got.

#5 add rollout status for asts
  README.md
  pkg/cmd/migrate/migrate.go
  pkg/cmd/rollout/rollout.go
  pkg/cmd/rollout/rollout_history.go
  pkg/cmd/rollout/rollout_pause.go
  pkg/cmd/rollout/rollout_restart.go
  pkg/cmd/rollout/rollout_resume.go
  pkg/cmd/rollout/rollout_status.go
  pkg/internal/polymorphichelpers/rollback.go
  pkg/internal/polymorphichelpers/rollout_status.go
Labels: lgtm

#7 add more todo cmd
  README.md
Labels: approved, lgtm, size/S

#6 Update the var validArg and comments
  README.md
  pkg/cmd/rollout/rollout_history.go
  pkg/cmd/rollout/rollout_restart.go
  pkg/cmd/rollout/rollout_undo.go
Labels: approved, lgtm, size/XS
