Repository openkruise/kruise-tools, pull requests merged in 2021-09, with the labels that each got.

#17 support advanced statefulset and allow --local option
  pkg/cmd/set/README.md
  pkg/cmd/set/set_env.go
  pkg/cmd/set/set_image.go
  pkg/cmd/set/set_resources.go
  pkg/cmd/util/factory_client_access.go
  pkg/internal/polymorphichelpers/updatepodspec.go
Labels: lgtm, approved, size/L

#19 Feature/restart clone inplace
  README.md
  pkg/cmd/migrate/migrate.go
  pkg/cmd/rollout/rollout_restart.go
  pkg/cmd/set/set_env.go
  pkg/cmd/set/set_image.go
  pkg/cmd/set/set_resources.go
  pkg/cmd/util/helpers.go
  pkg/internal/polymorphichelpers/helpers.go
  pkg/internal/polymorphichelpers/objectrestarter.go
Labels: lgtm, approved, size/L

#21 fix test bug
  pkg/cmd/set/set_env.go
  pkg/cmd/set/set_env_test.go
  pkg/cmd/set/set_resources.go
Labels: lgtm, size/S, approved

#23 Add worklow for release
  .github/workflows/release.yaml
  .golangci.yml
  go.mod
  go.sum
Labels: size/L
