Repository openkruise/kruise-tools, pull requests merged in 2022-01, with the labels that each got.

#39 Support exec current working sidecar container
  README.md
  go.mod
  pkg/cmd/cmd.go
  pkg/cmd/exec/exec.go
  pkg/cmd/exec/exec_test.go
  pkg/cmd/util/factory_client_access.go
  pkg/cmd/util/sidecar_set.go
  pkg/internal/polymorphichelpers/helpers.go
Labels: lgtm, approved, size/XL

#40 Auto update plugin by krew index
  .github/workflows/release.yaml
Labels: lgtm, approved, size/XS

#42 auth support
  go.mod
  go.sum
  pkg/cmd/cmd.go
Labels: lgtm, size/S, approved
