Repository openkruise/kruise-tools, pull requests merged in 2022-10, with the labels that each got.

#69 feat: add resourcedistribution generator
  cmd/resourcedistributiongenerator/Makefile
  cmd/resourcedistributiongenerator/README.md
  cmd/resourcedistributiongenerator/generator/alias.go
  cmd/resourcedistributiongenerator/generator/resourcedistribution.go
  cmd/resourcedistributiongenerator/generator/targets.go
  cmd/resourcedistributiongenerator/generator/utils.go
  cmd/resourcedistributiongenerator/go.mod
  cmd/resourcedistributiongenerator/go.sum
  cmd/resourcedistributiongenerator/main.go
  cmd/resourcedistributiongenerator/main_test.go
Labels: lgtm, approved, size/XXL

#71 Fix ads patch for rollout undo
  pkg/internal/polymorphichelpers/rollback.go
Labels: lgtm, approved

#70 merge resourcedistribution generator mods and makefiles
  .github/workflows/release.yaml
  Makefile
  cmd/resourcedistributiongenerator/Makefile
  cmd/resourcedistributiongenerator/README.md
  cmd/resourcedistributiongenerator/generator/resourcedistribution.go
  cmd/resourcedistributiongenerator/generator/targets.go
  cmd/resourcedistributiongenerator/go.mod
  cmd/resourcedistributiongenerator/go.sum
  cmd/resourcedistributiongenerator/main.go
  cmd/resourcedistributiongenerator/main_test.go
  go.mod
  go.sum
Labels: lgtm, approved, size/XL
